### ISSUE TITLE
cannot connect to mosquitto : Client wordclock disconnected, not authorised.

### ISSUE THREAD

**Issue by bonjour81** [t0mg/wordclock#51]
Hello,

I am trying to use mqtt connexion, but it won't connect to my broker.
I see this error message on broker:  `Client wordclock disconnected, not authorised.`

Any idea what could cause this ?

I tried 2 different username/password without success.

is there any restriction in password format for mqtt?

I use last release 2.2 and nodo hardware.

**Comment by Thunfeld** [comment]
Hi,

I got the same message at first when I tried it without any username or password.
However, I now use the following configuration, and it is working:

1. Go to Add-ons -> MQTT and look for the Configuration tab.
2. Look for Options and edit the YAML using the button in the top-right corner.
3. Add the following code:

```
logins:
  - username: user
    password: password
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: false
  folder: mosquitto
```
Try this for now and let me know if it works.

Best regards,
