### ISSUE TITLE
Cant see ldr value in Homeassistat

### ISSUE THREAD

**Issue by JayPi01** [t0mg/wordclock#54]
Hi,

In my nodo Web UI I  enabled and configured the mqtt client connection and it works fine.
Then I configured  HomeAssistant as described in the manual:

mqtt:
  - light:
      name: "Wordclock"
      availability_topic: "wordclock/availability"
      state_topic: "wordclock/light/switch"
      command_topic: "wordclock/light/switch/set"
      rgb_state_topic: "wordclock/light/color"
      rgb_command_topic: "wordclock/light/color/set"
      qos: 0
      optimistic: false
  - sensor:
      name: "Light sensor"
      availability_topic: "wordclock/availability"
      state_topic: "wordclock/sensor/ldr"

In HomeAssistant I can see the 'wordclock/light' entity and I can set color and on/off.
But unfortunately the 'sensor' entity is not visible. Any ideas?

**Comment by t0mg** [comment]
Hey, sorry I can't reproduce your issue. Did you figure it out?

**Comment by JayPi01** [comment]
Kind of...
When I comment out the line 'state_topic: "wordclock/sensor/ldr"'' it works.

**Comment by t0mg** [comment]
Thanks for letting us know. I don't understand what's going on though 😅

**Comment by t0mg** [comment]
Thanks, I've updated the documentation!

**Comment by rubenvandeven** [comment]
Thanks for the quick update! 
Homeassistant drew the measurement as a discrete value, showing blocks instead of a graph. Apparently, that is the default if there's no 'unit of measurement' specified for the sensor. To render the value as a graph changed it as such:

```yaml
  sensor:
      - name: "Wordclock Light sensor"
        availability_topic: "wordclock/availability"
        state_topic: "wordclock/sensor/ldr"
        unit_of_measurement: "%"
        value_template: "{{ sqrt(value | float + 1) * 100 / sqrt(1024 + 1) }}"
```

The square root in the `value_template` distributes the values a bit nicer on the curve.
